package com.tembus.customer.ui.localization

import androidx.compose.material3.LocalTextStyle
import androidx.compose.material3.Text as MaterialText
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.TextLayoutResult
import androidx.compose.ui.text.AnnotatedString
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontStyle
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.text.style.TextDecoration
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.TextUnit
import java.util.Locale

/**
 * Temporary central boundary for legacy hardcoded customer copy.
 * API/server values are deliberately passed through unchanged.
 */
object CustomerTextCatalog {
    private val englishTranslations = mapOf(
        "Beranda" to "Home",
        "Pesanan" to "Orders",
        "Riwayat" to "History",
        "Riwayat Pesanan" to "Order History",
        "Profil" to "Profile",
        "Notifikasi" to "Notifications",
        "Alamat" to "Addresses",
        "Alamat tersimpan" to "Saved addresses",
        "Favorit" to "Favorites",
        "Keranjang" to "Cart",
        "Mau apa hari ini?" to "What would you like today?",
        "Layanan" to "Services",
        "Food Delivery" to "Food Delivery",
        "Tambal Ban" to "Tire Repair",
        "Towing" to "Towing",
        "Merchant terdekat" to "Nearby merchants",
        "Pilih layanan" to "Choose a service",
        "Pilih tujuan" to "Choose a destination",
        "Mulai Order Baru" to "Start a New Order",
        "Rute & estimasi" to "Route & estimate",
        "Lacak Posisi Kurir" to "Track Courier",
        "Rute sedang dihitung" to "Calculating route",
        "Rute sedang dimuat" to "Loading route",
        "Pesanan tertunda sedang disinkronkan." to "Pending orders are syncing.",
        "Tidak ada petugas tersedia di sekitar Anda" to "No providers are available nearby",
        "Belum ada merchant di sekitarmu" to "No merchants nearby",
        "Belum ada merchant favorit" to "No favorite merchants",
        "Belum ada kurir tersedia" to "No couriers available",
        "Belum ada menu" to "No menu items",
        "Bahasa" to "Language",
        "Kembali" to "Back",
        "Tutup" to "Close",
        "Batal" to "Cancel",
        "Simpan" to "Save",
        "Kirim" to "Send",
        "Lanjut" to "Continue",
        "Selesai" to "Done",
        "Coba Lagi" to "Try Again",
        "Hapus" to "Delete",
        "Edit" to "Edit",
        "Detail" to "Details",
        "Lihat Detail" to "View Details",
        "Pesan Lagi" to "Order Again",
        "Pilih" to "Choose",
        "Cari" to "Search",
        "Muat ulang" to "Refresh",
        "Memuat..." to "Loading...",
        "Tidak ada data" to "No data",
        "Belum ada pesanan" to "No orders yet",
        "Belum ada notifikasi" to "No notifications yet",
        "Belum ada alamat" to "No addresses yet",
        "Email" to "Email",
        "Password" to "Password",
        "Masuk" to "Sign in",
        "Daftar" to "Register",
        "Keluar" to "Sign out",
        "Simpan Perubahan" to "Save Changes",
        "Tambah Alamat" to "Add Address",
        "Alamat Pengiriman" to "Delivery Address",
        "Alamat Pickup" to "Pickup Address",
        "Catatan" to "Notes",
        "Catatan (opsional)" to "Notes (optional)",
        "Nama penerima" to "Recipient name",
        "Nomor handphone penerima" to "Recipient phone number",
        "Alamat Pengantaran" to "Delivery Address",
        "Harga final dihitung dari jarak, berat, dan fitur tambahan." to "Final price is calculated from distance, weight, and add-ons.",
        "Harga Barang (Rp)" to "Item Value (IDR)",
        "Harga Jasa (Rp)" to "Service Price (IDR)",
        "Harga" to "Price",
        "Total" to "Total",
        "Pembayaran" to "Payment",
        "Bayar Sekarang" to "Pay Now",
        "Metode Pembayaran" to "Payment Method",
        "Status Pesanan" to "Order Status",
        "Lacak Pesanan" to "Track Order",
        "Rincian Pesanan" to "Order Details",
        "Ringkasan Pesanan" to "Order Summary",
        "Rincian Pembayaran" to "Payment Details",
        "Pesanan Diproses" to "Order is being processed",
        "Pesanan Selesai" to "Order completed",
        "Pesanan Dibatalkan" to "Order cancelled",
        "Panggilan dalam aplikasi" to "In-app call",
        "Menghubungkan panggilan" to "Connecting call",
        "Panggilan masuk" to "Incoming call",
        "Panggilan tersambung" to "Call connected",
        "Akhiri" to "End",
        "Terima" to "Accept",
        "Tolak" to "Decline",
        "Konfirmasi" to "Confirm",
        "Konfirmasi Keluar" to "Confirm Sign out",
        "Pilih hasil pencarian" to "Choose a search result",
        "Bersihkan" to "Clear",
        "Kurangi" to "Decrease",
        "Tambah" to "Add",
        "Error" to "Error",
        "Foto Barang" to "Item Photo",
        "Foto kurir" to "Courier photo",
        "Kurir" to "Courier",
        "Telepon kurir" to "Call courier",
        "Opsi lainnya" to "More options",
        "Tambah lampiran" to "Add attachment",
        "Foto makanan" to "Food photo",
        "Salin nomor pesanan" to "Copy order number",
        "Foto Profil Kurir" to "Courier profile photo",
        "Panggil" to "Call",
        "Pesan" to "Message",
        "Arsipkan" to "Archive",
        "Ingatkan nanti" to "Remind me later",
        "Sukses" to "Success",
        "Hapus dari favorit" to "Remove from favorites",
        "Tutup pembayaran" to "Close payment",
        "Mikrofon" to "Microphone",
        "Panggilan dalam aplikasi" to "In-app call",
        "Dipilih" to "Selected",
        "Layar Aman" to "Secure screen",
        "Salin" to "Copy",
        "Keranjang masih kosong" to "Your cart is empty",
        "Belum Ada Riwayat" to "No History Yet",
        "Buka Chat" to "Open Chat",
        "Buka Maps" to "Open Maps",
        "Izinkan Kamera" to "Allow Camera",
        "Izinkan Lokasi" to "Allow Location",
        "Coba lagi" to "Try again",
        "Terjadi kesalahan" to "Something went wrong",
        // UIUX-2026-004: kunci layar audit (dashboard, tambal, food, tracking).
        "Cari layanan, makanan..." to "Search services, food...",
        "Saldo siap dipakai" to "Balance ready to use",
        "Bayar" to "Pay",
        "Top Up" to "Top Up",
        "Lainnya" to "More",
        "Layanan utama TEMBUS, satu tap ke pesanan." to "TEMBUS core services, one tap to order.",
        "Paket Instan" to "Instant Courier",
        "Ekspedisi Antar Kota" to "Intercity Shipping",
        "Ekspedisi Antar-Kota" to "Intercity Shipping",
        "Layanan TEMBUS" to "TEMBUS Services",
        "Cepat • ETA sesuai rute" to "Fast • route-based ETA",
        "Hemat • ETA terjadwal" to "Budget • scheduled ETA",
        "Aktifkan update kurir" to "Enable courier updates",
        "Dapatkan alert saat kurir diterima, 5 menit dari lokasi, dan chat baru masuk." to "Get alerts when your courier is assigned, 5 minutes away, and on new chats.",
        "Aktifkan notifikasi" to "Enable notifications",
        "Nanti" to "Later",
        "Bisnis" to "Business",
        "Pesanan Sedang Berjalan" to "Active Order",
        "Lacak" to "Track",
        "Siap melayani" to "Ready to serve",
        "Data sedang disinkronkan" to "Syncing data",
        "Layanan Populer" to "Popular services",
        "Darurat" to "Emergency",
        "Cari teknisi atau layanan" to "Search technicians or services",
        "Teknisi Terdekat" to "Nearby technicians",
        "Tidak ada teknisi tersedia di sekitar Anda" to "No technicians available nearby",
        "Detail Teknisi" to "Technician details",
        "Pesan Teknisi Ini" to "Book this technician",
        "Alternatif towing terdekat" to "Nearby towing alternatives",
        "Petugas towing live dari lokasi GPS Anda jika layanan tambal ban tidak sesuai." to "Live towing providers from your GPS location if tire repair does not fit.",
        "Pilih Petugas" to "Choose provider",
        "Perbaiki" to "Adjust pin",
        "Tujuan dipilih" to "Destination selected",
        "Tujuan towing" to "Towing destination",
        "Kontak tujuan" to "Destination contact",
        "Nama bengkel/penerima" to "Shop/recipient name",
        "Nomor kontak tujuan (wajib)" to "Destination contact number (required)",
        "Aktifkan Lokasi" to "Enable Location",
        "Aktifkan lokasi untuk menentukan posisi Anda." to "Enable location to determine your position.",
        "Cari alamat bengkel, rumah, atau dropoff" to "Search shop, home, or dropoff address",
        "Membaca alamat dari GPS..." to "Reading address from GPS...",
        "Mengambil lokasi..." to "Getting location...",
        "Material tambahan (opsional)" to "Additional materials (optional)",
        "Harga diambil dari katalog operasional dan dihitung ulang server saat cek harga." to "Price comes from the operations catalog and is recalculated by the server at checkout.",
        "Jarak" to "Distance",
        "Estimasi tiba" to "Estimated arrival",
        "Kendaraan" to "Vehicle",
        "Harga jasa" to "Service fee",
        "Jangkauan" to "Coverage",
        "Harga jasa ditentukan oleh petugas. Biaya per-km dan tol ditentukan oleh sistem." to "Service fee is set by the provider. Per-km and toll charges are set by the system.",
        "Cari makanan" to "Search food",
        "Semua" to "All",
        "Terdekat" to "Nearest",
        "Populer" to "Popular",
        "Buka" to "Open",
        "Gagal memuat merchant" to "Failed to load merchants",
        "Camilan" to "Snacks",
        "Makanan" to "Meals",
        "Ramah Kurir Sepeda" to "Bike-courier friendly",
        "Ganti merchant?" to "Switch merchant?",
        "Lihat" to "View",
        "Checkout" to "Checkout",
        "Jelaskan situasi" to "Describe the situation",
        "Kirim SOS" to "Send SOS",
        "Konfirmasi SOS" to "Confirm SOS",
        "Laporkan isu" to "Report an issue",
        "SOS / eskalasi" to "SOS / escalation",
        "Safety Center" to "Safety Center",
        "SOS akan membuat insiden CRITICAL dan mengirimkannya ke jalur eskalasi market. Jika vendor belum tersedia, aplikasi hanya mencatat insiden dan menampilkan instruksi darurat yang disetujui (tidak ada respons yang dijanjikan)." to "SOS creates a CRITICAL incident and routes it to market escalation. If no vendor is available, the app only records the incident and shows approved emergency instructions (no response promised).",
        "Tetap tersedia selama order aktif. Laporan safety membuat insiden terpisah dan tidak mengubah status order secara diam-diam." to "Remains available while the order is active. A safety report creates a separate incident and never silently changes the order status.",
        "Contoh: lokasi pickup terasa tidak aman" to "Example: pickup location feels unsafe",
        "Buat Pesanan" to "Place Order",
        "Tambal Ban Motor" to "Motorcycle Tire Repair",
        "Tambal Ban Mobil" to "Car Tire Repair",
        "Pesan Teknisi Ini" to "Book This Technician",
        "Tipe Kendaraan" to "Vehicle type",
        "Jenis Kerusakan" to "Damage type",
        "Merek kendaraan" to "Vehicle brand",
        "Model kendaraan" to "Vehicle model",
        "Kondisi kendaraan" to "Vehicle condition",
        "Akses dan kendala lokasi" to "Location access & constraints",
        "Bisa berjalan" to "Can still roll",
        "Tidak bisa berjalan" to "Cannot roll",
        "Rusak berat" to "Heavily damaged",
        "Kondisi tidak diketahui" to "Condition unknown",
        "Ban Bocor" to "Flat tire",
        "Ban Pecah" to "Blown tire",
        "Ban Aus" to "Worn tire",
        "Kendala Lainnya" to "Other issue",
        "Matic" to "Scooter",
        "Bebek" to "Underbone",
        "Sport" to "Sport",
        "1. Kendaraan & masalah" to "1. Vehicle & issue",
        "2. Lokasi layanan" to "2. Service location",
        "Petugas dipilih" to "Provider selected",
        "Cek Harga" to "Check Price",
        "Pesan Sekarang" to "Order Now",
        "Lokasi masalah, kapabilitas teknisi, dan ETA untuk jalur bantuan terpendek." to "Issue location, technician capability, and ETA for the shortest help route.",
    )

    fun translate(text: String): String {
        if (Locale.getDefault().language != "en") return text
        englishTranslations[text]?.let { return it }
        return when {
            text.startsWith("Pesanan #") -> text.replaceFirst("Pesanan #", "Order #")
            text.startsWith("Foto ") -> "Photo ${text.removePrefix("Foto ")}"
            text.endsWith(" bintang") -> "${text.removeSuffix(" bintang")} stars"
            text.endsWith(" menit") -> "${text.removeSuffix(" menit")} minutes"
            else -> text
        }
    }
}

@Composable
fun CustomerText(
    text: String,
    modifier: Modifier = Modifier,
    color: Color = Color.Unspecified,
    fontSize: TextUnit = TextUnit.Unspecified,
    fontStyle: FontStyle? = null,
    fontWeight: FontWeight? = null,
    fontFamily: FontFamily? = null,
    letterSpacing: TextUnit = TextUnit.Unspecified,
    textDecoration: TextDecoration? = null,
    textAlign: TextAlign? = null,
    lineHeight: TextUnit = TextUnit.Unspecified,
    overflow: TextOverflow = TextOverflow.Clip,
    softWrap: Boolean = true,
    maxLines: Int = Int.MAX_VALUE,
    minLines: Int = 1,
    onTextLayout: (TextLayoutResult) -> Unit = {},
    style: TextStyle = LocalTextStyle.current,
) {
    MaterialText(
        text = CustomerTextCatalog.translate(text),
        modifier = modifier,
        color = color,
        fontSize = fontSize,
        fontStyle = fontStyle,
        fontWeight = fontWeight,
        fontFamily = fontFamily,
        letterSpacing = letterSpacing,
        textDecoration = textDecoration,
        textAlign = textAlign,
        lineHeight = lineHeight,
        overflow = overflow,
        softWrap = softWrap,
        maxLines = maxLines,
        minLines = minLines,
        onTextLayout = onTextLayout,
        style = style,
    )
}

@Composable
fun CustomerText(
    text: AnnotatedString,
    modifier: Modifier = Modifier,
    color: Color = Color.Unspecified,
    fontSize: TextUnit = TextUnit.Unspecified,
    fontStyle: FontStyle? = null,
    fontWeight: FontWeight? = null,
    fontFamily: FontFamily? = null,
    letterSpacing: TextUnit = TextUnit.Unspecified,
    textDecoration: TextDecoration? = null,
    textAlign: TextAlign? = null,
    lineHeight: TextUnit = TextUnit.Unspecified,
    overflow: TextOverflow = TextOverflow.Clip,
    softWrap: Boolean = true,
    maxLines: Int = Int.MAX_VALUE,
    minLines: Int = 1,
    onTextLayout: (TextLayoutResult) -> Unit = {},
    style: TextStyle = LocalTextStyle.current,
) {
    MaterialText(
        text = text,
        modifier = modifier,
        color = color,
        fontSize = fontSize,
        fontStyle = fontStyle,
        fontWeight = fontWeight,
        fontFamily = fontFamily,
        letterSpacing = letterSpacing,
        textDecoration = textDecoration,
        textAlign = textAlign,
        lineHeight = lineHeight,
        overflow = overflow,
        softWrap = softWrap,
        maxLines = maxLines,
        minLines = minLines,
        onTextLayout = onTextLayout,
        style = style,
    )
}
