package domain

import (
	"context"
	"crypto/hmac"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"math"
	"os"
	"regexp"
	"sort"
	"strings"
	"time"
)

// RiskSignalCategory is the governed vocabulary for risk inputs. Signals are
// deliberately coarse: exact addresses, coordinates, names, phone numbers,
// and other sensitive attributes never enter the decision payload.
type RiskSignalCategory string

const (
	RiskSignalAccount   RiskSignalCategory = "account"
	RiskSignalDevice    RiskSignalCategory = "device"
	RiskSignalPayment   RiskSignalCategory = "payment"
	RiskSignalPromo     RiskSignalCategory = "promo"
	RiskSignalGPS       RiskSignalCategory = "gps"
	RiskSignalHandoff   RiskSignalCategory = "handoff"
	RiskSignalRefund    RiskSignalCategory = "refund"
	RiskSignalClaim     RiskSignalCategory = "claim"
	RiskSignalProvider  RiskSignalCategory = "provider"
	RiskSignalCollusion RiskSignalCategory = "collusion"
)

// RiskDecisionType is the only decision vocabulary exposed to transactional
// callers and operations. It is intentionally independent from order status.
type RiskDecisionType string

const (
	RiskDecisionAllow     RiskDecisionType = "ALLOW"
	RiskDecisionChallenge RiskDecisionType = "CHALLENGE"
	RiskDecisionReview    RiskDecisionType = "REVIEW"
	RiskDecisionHold      RiskDecisionType = "HOLD"
	RiskDecisionBlock     RiskDecisionType = "BLOCK"
)

type RiskOperation string

const (
	RiskOperationOrderCreate          RiskOperation = "order_create"
	RiskOperationFoodOrderCreate      RiskOperation = "food_order_create"
	RiskOperationDispatchAccept       RiskOperation = "dispatch_accept"
	RiskOperationPaymentAuthorization RiskOperation = "payment_authorization"
	RiskOperationRefundRequest        RiskOperation = "refund_request"
	RiskOperationClaimSubmission      RiskOperation = "claim_submission"
	RiskOperationProviderCallback     RiskOperation = "provider_callback"
	RiskOperationHandoffDelivery      RiskOperation = "handoff_delivery"
	RiskOperationPayoutRequest        RiskOperation = "payout_request"
)

type RiskFailureMode string

const (
	RiskFailureNormal       RiskFailureMode = "normal"
	RiskFailureTimeout      RiskFailureMode = "timeout"
	RiskFailureEngineError  RiskFailureMode = "engine_error"
	RiskFailurePersistError RiskFailureMode = "persist_error"
)

var (
	ErrInvalidRiskRequest = errors.New("invalid risk evaluation request")
	ErrInvalidRiskSignal  = errors.New("invalid risk signal")
	validRiskCode         = regexp.MustCompile(`^[a-z0-9][a-z0-9._:-]{1,95}$`)
	validRiskReason       = regexp.MustCompile(`^[a-z0-9][a-z0-9._:-]{1,95}$`)
)

// RiskPolicy is loaded per market and operation from system_configs. The
// defaults are conservative for money/evidence operations and fail-open only
// where a risk outage must not strand a non-financial customer flow.
type RiskPolicy struct {
	MarketCode       string          `json:"market_code"`
	Operation        RiskOperation   `json:"operation"`
	Version          string          `json:"version"`
	TimeoutMillis    int             `json:"timeout_millis"`
	OnTimeout        RiskFailureMode `json:"on_timeout"`
	OnEngineError    RiskFailureMode `json:"on_engine_error"`
	ChallengeScore   float64         `json:"challenge_score"`
	ReviewScore      float64         `json:"review_score"`
	HoldScore        float64         `json:"hold_score"`
	BlockScore       float64         `json:"block_score"`
	SensitiveAllowed bool            `json:"sensitive_attributes_allowed"`
}

func DefaultRiskPolicy(market string, operation RiskOperation) RiskPolicy {
	market = normalizeMarketCode(market)
	failClosed := operation == RiskOperationPaymentAuthorization ||
		operation == RiskOperationRefundRequest ||
		operation == RiskOperationClaimSubmission ||
		operation == RiskOperationProviderCallback ||
		operation == RiskOperationPayoutRequest ||
		operation == RiskOperationHandoffDelivery
	onFailure := RiskFailureMode("fail_open")
	if failClosed {
		onFailure = "fail_closed"
	}
	return RiskPolicy{
		MarketCode:       market,
		Operation:        operation,
		Version:          "risk-rules-2026-09-09-v1",
		TimeoutMillis:    250,
		OnTimeout:        onFailure,
		OnEngineError:    onFailure,
		ChallengeScore:   20,
		ReviewScore:      45,
		HoldScore:        70,
		BlockScore:       90,
		SensitiveAllowed: false,
	}
}

// RiskSignal is an auditable, coarse-grained observation. SubjectKeyHash is
// generated by the service and is never accepted from client input.
type RiskSignal struct {
	Category       RiskSignalCategory `json:"category"`
	Code           string             `json:"code"`
	Score          float64            `json:"score"`
	Source         string             `json:"source"`
	SubjectKeyHash string             `json:"subject_key_hash,omitempty"`
	Attributes     map[string]string  `json:"attributes,omitempty"`
	ObservedAt     time.Time          `json:"observed_at"`
}

type RiskEvaluationRequest struct {
	Operation      RiskOperation `json:"operation"`
	MarketCode     string        `json:"market_code"`
	EntityType     string        `json:"entity_type"`
	EntityID       string        `json:"entity_id"`
	SubjectID      string        `json:"-"`
	CorrelationID  string        `json:"correlation_id"`
	IdempotencyKey string        `json:"idempotency_key"`
	Signals        []RiskSignal  `json:"signals"`
}

type RiskDecision struct {
	ID             string           `json:"id"`
	Operation      RiskOperation    `json:"operation"`
	MarketCode     string           `json:"market_code"`
	EntityType     string           `json:"entity_type"`
	EntityID       string           `json:"entity_id"`
	SubjectKeyHash string           `json:"subject_key_hash"`
	Decision       RiskDecisionType `json:"decision"`
	RiskScore      float64          `json:"risk_score"`
	ReasonCodes    []string         `json:"reason_codes"`
	Signals        []RiskSignal     `json:"signals"`
	PolicyVersion  string           `json:"policy_version"`
	FailureMode    RiskFailureMode  `json:"failure_mode"`
	CorrelationID  string           `json:"correlation_id"`
	IdempotencyKey string           `json:"-"`
	CreatedAt      time.Time        `json:"created_at"`
}

type RiskManualReview struct {
	ID             string            `json:"id"`
	RiskDecisionID string            `json:"risk_decision_id"`
	Status         string            `json:"status"`
	Evidence       json.RawMessage   `json:"evidence"`
	ReviewerID     *string           `json:"reviewer_id,omitempty"`
	Decision       *RiskDecisionType `json:"decision,omitempty"`
	Reason         *string           `json:"reason,omitempty"`
	ReviewedAt     *time.Time        `json:"reviewed_at,omitempty"`
	CreatedAt      time.Time         `json:"created_at"`
	UpdatedAt      time.Time         `json:"updated_at"`
}

type RiskRepository interface {
	SaveRiskDecision(ctx context.Context, decision *RiskDecision, reviewEvidence json.RawMessage) error
}

type RiskService interface {
	Evaluate(ctx context.Context, request RiskEvaluationRequest) (RiskDecision, error)
}

type RiskModelResult struct {
	AdditionalScore float64
	Signals         []RiskSignal
}

type RiskModel interface {
	Evaluate(ctx context.Context, request RiskEvaluationRequest) (RiskModelResult, error)
}

var sensitiveRiskAttributes = map[string]struct{}{
	"age": {}, "address": {}, "date_of_birth": {}, "email": {}, "ethnicity": {},
	"gender": {}, "health": {}, "name": {}, "phone": {}, "religion": {},
	"race": {}, "exact_coordinates": {}, "exact_location": {}, "national_id": {},
}

var allowedRiskAttributes = map[string]struct{}{
	"amount_band": {}, "currency": {}, "device_reputation_band": {}, "gps_integrity": {},
	"handoff_distance_band": {}, "ip_reputation_band": {}, "market_code": {},
	"order_age_band": {}, "provider_code": {}, "service_code": {}, "velocity_band": {},
}

func (r RiskSignal) Validate() error {
	if !validRiskCategory(r.Category) || !validRiskCode.MatchString(strings.TrimSpace(r.Code)) ||
		!validRiskCode.MatchString(strings.TrimSpace(r.Source)) || math.IsNaN(r.Score) || math.IsInf(r.Score, 0) || r.Score < 0 || r.Score > 100 {
		return ErrInvalidRiskSignal
	}
	for key := range r.Attributes {
		key = strings.ToLower(strings.TrimSpace(key))
		if _, forbidden := sensitiveRiskAttributes[key]; forbidden {
			return fmt.Errorf("%w: sensitive attribute %s is not governed", ErrInvalidRiskSignal, key)
		}
		if _, allowed := allowedRiskAttributes[key]; !allowed {
			return fmt.Errorf("%w: attribute %s is not allowlisted", ErrInvalidRiskSignal, key)
		}
	}
	return nil
}

func (r RiskEvaluationRequest) Validate(policy RiskPolicy) error {
	if strings.TrimSpace(string(r.Operation)) == "" || strings.TrimSpace(r.MarketCode) == "" ||
		strings.TrimSpace(r.EntityType) == "" || strings.TrimSpace(r.EntityID) == "" || strings.TrimSpace(r.SubjectID) == "" {
		return ErrInvalidRiskRequest
	}
	if policy.SensitiveAllowed {
		return fmt.Errorf("%w: sensitive attributes cannot be enabled by runtime policy", ErrInvalidRiskRequest)
	}
	for _, signal := range r.Signals {
		if err := signal.Validate(); err != nil {
			return err
		}
	}
	return nil
}

func AssessRisk(request RiskEvaluationRequest, policy RiskPolicy, modelResult *RiskModelResult) (RiskDecision, error) {
	if err := request.Validate(policy); err != nil {
		return RiskDecision{}, err
	}
	allSignals := append([]RiskSignal(nil), request.Signals...)
	if modelResult != nil {
		if math.IsNaN(modelResult.AdditionalScore) || math.IsInf(modelResult.AdditionalScore, 0) || modelResult.AdditionalScore < 0 || modelResult.AdditionalScore > 100 {
			return RiskDecision{}, fmt.Errorf("%w: model score is invalid", ErrInvalidRiskRequest)
		}
		for _, signal := range modelResult.Signals {
			if err := signal.Validate(); err != nil {
				return RiskDecision{}, err
			}
		}
		allSignals = append(allSignals, modelResult.Signals...)
	}

	sort.SliceStable(allSignals, func(i, j int) bool {
		if allSignals[i].Category != allSignals[j].Category {
			return allSignals[i].Category < allSignals[j].Category
		}
		return allSignals[i].Code < allSignals[j].Code
	})

	score := 0.0
	reasons := make([]string, 0, len(allSignals))
	hardBlock := false
	for _, signal := range allSignals {
		score += signal.Score
		reason := standardReasonCode(signal.Category, signal.Code)
		if signal.Score > 0 && !containsString(reasons, reason) {
			reasons = append(reasons, reason)
		}
		if isHardBlockSignal(signal) {
			hardBlock = true
		}
	}
	if modelResult != nil {
		score += modelResult.AdditionalScore
	}
	score = math.Min(math.Max(score, 0), 100)
	decision := decisionForScore(score, policy)
	if hardBlock {
		decision = RiskDecisionBlock
	}
	if len(reasons) == 0 {
		reasons = []string{"risk.no_positive_signal"}
	}
	return RiskDecision{
		Operation:     request.Operation,
		MarketCode:    normalizeMarketCode(request.MarketCode),
		EntityType:    strings.TrimSpace(request.EntityType),
		EntityID:      strings.TrimSpace(request.EntityID),
		Decision:      decision,
		RiskScore:     score,
		ReasonCodes:   reasons,
		Signals:       allSignals,
		PolicyVersion: policy.Version,
		FailureMode:   RiskFailureNormal,
		CorrelationID: strings.TrimSpace(request.CorrelationID),
	}, nil
}

func FallbackRiskDecision(request RiskEvaluationRequest, policy RiskPolicy, mode RiskFailureMode, reason string) RiskDecision {
	decision := RiskDecisionAllow
	if mode == RiskFailureMode("fail_closed") {
		decision = RiskDecisionHold
	}
	return RiskDecision{
		Operation:     request.Operation,
		MarketCode:    normalizeMarketCode(request.MarketCode),
		EntityType:    strings.TrimSpace(request.EntityType),
		EntityID:      strings.TrimSpace(request.EntityID),
		Decision:      decision,
		ReasonCodes:   []string{reason},
		PolicyVersion: policy.Version,
		FailureMode:   mode,
		CorrelationID: strings.TrimSpace(request.CorrelationID),
	}
}

func HashRiskSubject(subject string) string {
	key := strings.TrimSpace(os.Getenv("RISK_PSEUDONYM_KEY"))
	if key == "" {
		key = strings.TrimSpace(os.Getenv("EVENT_ACTOR_PSEUDONYM_KEY"))
	}
	if key == "" {
		sum := sha256.Sum256([]byte(subject))
		return hex.EncodeToString(sum[:])
	}
	mac := hmac.New(sha256.New, []byte(key))
	_, _ = mac.Write([]byte(subject))
	return hex.EncodeToString(mac.Sum(nil))
}

func normalizeMarketCode(market string) string {
	market = strings.ToLower(strings.TrimSpace(market))
	if market == "" {
		return "id-jk"
	}
	return market
}

func validRiskCategory(category RiskSignalCategory) bool {
	switch category {
	case RiskSignalAccount, RiskSignalDevice, RiskSignalPayment, RiskSignalPromo, RiskSignalGPS,
		RiskSignalHandoff, RiskSignalRefund, RiskSignalClaim, RiskSignalProvider, RiskSignalCollusion:
		return true
	default:
		return false
	}
}

func decisionForScore(score float64, policy RiskPolicy) RiskDecisionType {
	switch {
	case score >= policy.BlockScore:
		return RiskDecisionBlock
	case score >= policy.HoldScore:
		return RiskDecisionHold
	case score >= policy.ReviewScore:
		return RiskDecisionReview
	case score >= policy.ChallengeScore:
		return RiskDecisionChallenge
	default:
		return RiskDecisionAllow
	}
}

func isHardBlockSignal(signal RiskSignal) bool {
	switch strings.ToLower(strings.TrimSpace(signal.Code)) {
	case "account.suspended", "device.blocked", "payment.provider_invalid", "provider.webhook_invalid", "collusion.confirmed", "gps.spoof_confirmed":
		return true
	default:
		return false
	}
}

func standardReasonCode(category RiskSignalCategory, code string) string {
	code = strings.ToLower(strings.TrimSpace(code))
	if validRiskReason.MatchString(code) {
		return "risk." + code
	}
	return "risk." + string(category) + ".signal"
}

func containsString(values []string, target string) bool {
	for _, value := range values {
		if value == target {
			return true
		}
	}
	return false
}

func RiskReviewRequired(decision RiskDecisionType) bool {
	return decision == RiskDecisionReview || decision == RiskDecisionHold
}
