package domain

import "context"

// TrackingPollTarget is the durable provider/AWB pair that the integration
// gateway may poll. It is read from persisted orders, never generated by the
// polling worker.
type TrackingPollTarget struct {
	Provider string `json:"provider"`
	AWB      string `json:"awb_number"`
}

type TrackingPollTargetRepository interface {
	ListTrackingPollTargets(ctx context.Context) ([]TrackingPollTarget, error)
}
