import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Activity, AlertTriangle, CreditCard, Loader2, Megaphone, ShieldCheck } from 'lucide-react'
import { toast } from 'sonner'
import { api } from '../lib/api'

const inputClass = 'bg-surface-subtle border border-border rounded-xl p-3'
const formatMoney = (minor: number, currency = 'IDR') => `${currency} ${(Number(minor || 0) / 100).toLocaleString('id-ID')}`
const QueryState = ({ loading, error }: { loading: boolean; error: boolean }) => loading ? <Loader2 className="animate-spin" aria-label="Loading" /> : error ? <p className="text-sm text-danger">Data tidak tersedia. Cek API dan migrasi staging.</p> : null

export default function PlatformOperations() {
  const client = useQueryClient()
  const [healthDraft, setHealthDraft] = useState({ provider: '', state: 'degraded', reason: '' })
  const [reviewState, setReviewState] = useState<Record<string, string>>({})
  const [selectedIntentId, setSelectedIntentId] = useState<string | null>(null)
  const [selectedSafetyId, setSelectedSafetyId] = useState<string | null>(null)
  const [campaign, setCampaign] = useState({ campaign_code: '', market_code: 'id-jk', budget_minor: '0' })
  const paymentHealth = useQuery({ queryKey: ['platform-payment-health'], queryFn: async () => (await api.get('/admin/payment/health')).data?.data ?? [] })
  const paymentMethods = useQuery({ queryKey: ['platform-payment-methods'], queryFn: async () => (await api.get('/admin/payment/methods')).data?.data ?? [] })
  const paymentIntents = useQuery({ queryKey: ['platform-payment-intents'], queryFn: async () => (await api.get('/admin/payment/intents', { params: { limit: 30 } })).data?.data ?? [] })
  const paymentExceptions = useQuery({ queryKey: ['platform-payment-exceptions'], queryFn: async () => (await api.get('/admin/payment/exceptions')).data?.data ?? [] })
  const paymentChargebacks = useQuery({ queryKey: ['platform-payment-chargebacks'], queryFn: async () => (await api.get('/admin/payment/chargebacks')).data?.data ?? [] })
  const paymentTimeline = useQuery({ queryKey: ['platform-payment-timeline', selectedIntentId], enabled: Boolean(selectedIntentId), queryFn: async () => (await api.get(`/admin/payment/intents/${selectedIntentId}/events`)).data?.data ?? [] })
  const safety = useQuery({ queryKey: ['platform-safety'], queryFn: async () => (await api.get('/admin/safety/incidents', { params: { limit: 30 } })).data?.data ?? [] })
  const safetyDetail = useQuery({ queryKey: ['platform-safety-detail', selectedSafetyId], enabled: Boolean(selectedSafetyId), queryFn: async () => (await api.get(`/admin/safety/incidents/${selectedSafetyId}`)).data?.data ?? null })
  const reviews = useQuery({ queryKey: ['platform-reputation'], queryFn: async () => (await api.get('/admin/reputation/reviews', { params: { state: 'REPORTED', limit: 30 } })).data?.data ?? [] })
  const crm = useQuery({ queryKey: ['platform-crm'], queryFn: async () => (await api.get('/admin/crm/control-plane')).data?.data ?? { campaigns: [], loyalty: [], exceptions: [] } })
  const healthMutation = useMutation({ mutationFn: () => api.patch('/admin/payment/health', healthDraft), onSuccess: () => { toast.success('Provider health diperbarui'); client.invalidateQueries({ queryKey: ['platform-payment-health'] }) }, onError: () => toast.error('Provider health gagal diperbarui') })
  const reviewMutation = useMutation({ mutationFn: ({ id, state }: { id: string; state: string }) => api.patch(`/admin/reputation/reviews/${id}`, { state, reason: 'Admin moderation decision from queue' }), onSuccess: () => { toast.success('Review dimoderasi'); client.invalidateQueries({ queryKey: ['platform-reputation'] }) }, onError: () => toast.error('Moderasi review gagal') })
  const campaignMutation = useMutation({ mutationFn: () => api.post('/admin/crm/campaigns', { ...campaign, budget_minor: Number(campaign.budget_minor), audience_definition: {} }), onSuccess: () => { toast.success('Campaign draft dibuat'); setCampaign({ campaign_code: '', market_code: 'id-jk', budget_minor: '0' }); client.invalidateQueries({ queryKey: ['platform-crm'] }) }, onError: () => toast.error('Campaign gagal dibuat') })

  return <div className="space-y-8 animate-in" aria-labelledby="platform-operations-title">
    <header><h1 id="platform-operations-title" className="text-3xl font-black text-foreground-muted tracking-tight italic uppercase">Platform Operations</h1><p className="text-foreground-muted mt-1">Control plane staging untuk payment, safety, reputation, dan CRM. Semua angka berasal dari API admin; tidak ada data demo statis.</p></header>

    <section className="glass-card p-6 rounded-3xl border-border space-y-5" aria-labelledby="payment-ops-title">
      <div className="flex items-center gap-2"><CreditCard size={18} aria-hidden="true" /><h2 id="payment-ops-title" className="font-black uppercase tracking-wide">Payment orchestration</h2></div>
      <p className="text-sm text-foreground-muted">Intent dan event provider bersifat server-authoritative. Refund hanya dicatat sebagai request idempotent sampai adapter provider disetujui vendor.</p>
      <div className="grid gap-3 md:grid-cols-3"><input aria-label="Provider" className={inputClass} placeholder="provider code" value={healthDraft.provider} onChange={e => setHealthDraft({ ...healthDraft, provider: e.target.value })} /><select aria-label="Provider state" className={inputClass} value={healthDraft.state} onChange={e => setHealthDraft({ ...healthDraft, state: e.target.value })}><option value="healthy">Healthy</option><option value="degraded">Degraded</option><option value="disabled">Disabled</option></select><input aria-label="Health reason" className={inputClass} placeholder="Reason wajib" value={healthDraft.reason} onChange={e => setHealthDraft({ ...healthDraft, reason: e.target.value })} /><button type="button" disabled={healthMutation.isPending || !healthDraft.provider || !healthDraft.reason} onClick={() => healthMutation.mutate()} className="rounded-xl bg-primary text-on-primary p-3 font-bold md:col-span-3 disabled:opacity-50">Update provider health (TOTP)</button></div>
      <QueryState loading={paymentHealth.isLoading} error={Boolean(paymentHealth.error)} />
      <div className="grid gap-3 md:grid-cols-3">{paymentHealth.data?.map((item: any) => <div className="rounded-2xl bg-surface-subtle p-4" key={item.provider}><p className="font-bold">{item.provider}</p><p className="text-sm">{item.state} · new attempts {item.allow_new_attempts ? 'allowed' : 'blocked'}</p><p className="text-xs text-foreground-muted">{item.reason || '—'}</p></div>)}</div>
      <div className="rounded-2xl bg-surface-subtle p-4"><p className="font-bold">Market payment methods</p><p className="text-xs text-foreground-muted">Eligibility is resolved by market, currency, amount and remote enabled state.</p><div className="mt-2 grid gap-2 md:grid-cols-3">{paymentMethods.data?.map((item: any) => <div className="border border-border rounded-xl p-3" key={item.id}><p className="font-semibold">{item.payment_method} · {item.currency}</p><p className="text-xs">{item.market_code} · {item.provider} · {item.enabled ? 'enabled' : 'disabled'} · v{item.version}</p></div>)}</div></div>
      <div className="overflow-auto"><table className="w-full text-sm"><caption className="sr-only">Recent payment intents</caption><thead><tr className="text-left text-foreground-muted"><th className="p-2">Intent</th><th className="p-2">Order</th><th className="p-2">Amount</th><th className="p-2">State</th><th className="p-2">Provider reference</th><th className="p-2">Timeline</th></tr></thead><tbody>{paymentIntents.data?.map((item: any) => <tr className="border-t border-border" key={item.id}><td className="p-2 font-mono text-xs">{item.id}</td><td className="p-2 font-mono text-xs">{item.order_id}</td><td className="p-2">{formatMoney(item.amount_minor, item.currency)}</td><td className="p-2">{item.state}</td><td className="p-2">{item.provider_reference || '—'}</td><td className="p-2"><button type="button" className="underline" onClick={() => setSelectedIntentId(selectedIntentId === item.id ? null : item.id)}>{selectedIntentId === item.id ? 'Hide' : 'View'}</button></td></tr>)}</tbody></table></div>
      {selectedIntentId && <div className="rounded-2xl bg-surface-subtle p-4" aria-live="polite"><p className="font-bold">Intent timeline</p><QueryState loading={paymentTimeline.isLoading} error={Boolean(paymentTimeline.error)} /><div className="space-y-2">{paymentTimeline.data?.map((event: any) => <div className="text-sm border-l-2 border-primary pl-3" key={event.id}><p>{event.normalized_state} · {event.source}</p><p className="text-xs text-foreground-muted">{event.occurred_at} · provider status {event.provider_raw_status || '—'}</p></div>)}</div></div>}
      <p className="text-sm text-foreground-muted">Reconciliation exceptions: <strong>{paymentExceptions.data?.length ?? 0}</strong> · Chargebacks: <strong>{paymentChargebacks.data?.length ?? 0}</strong>. Detail provider raw status tetap dibatasi role dan audit.</p>
    </section>

    <section className="glass-card p-6 rounded-3xl border-border space-y-5" aria-labelledby="safety-ops-title">
      <div className="flex items-center gap-2"><ShieldCheck size={18} aria-hidden="true" /><h2 id="safety-ops-title" className="font-black uppercase tracking-wide">Safety incident queue</h2></div>
      <p className="text-sm text-foreground-muted">Safety adalah aggregate terpisah dari order. Perubahan state wajib role/TOTP dan tidak mengedit status order atau payment.</p><QueryState loading={safety.isLoading} error={Boolean(safety.error)} />
      <div className="space-y-2">{safety.data?.map((item: any) => <div className="rounded-2xl bg-surface-subtle p-4 flex flex-col md:flex-row md:items-center md:justify-between gap-3" key={item.id}><div><p className="font-bold">{item.severity} · {item.category}</p><p className="text-xs text-foreground-muted">{item.id} · SLA {item.sla_due_at ? new Date(item.sla_due_at).toLocaleString() : '—'}</p></div><div className="flex items-center gap-3"><span className="text-sm">{item.state}</span><button type="button" className="underline" onClick={() => setSelectedSafetyId(selectedSafetyId === item.id ? null : item.id)}>{selectedSafetyId === item.id ? 'Hide detail' : 'View detail'}</button></div></div>)}</div>
      {selectedSafetyId && <div className="rounded-2xl bg-surface-subtle p-4 space-y-3" aria-live="polite"><p className="font-bold">Safety incident timeline</p><QueryState loading={safetyDetail.isLoading} error={Boolean(safetyDetail.error)} />{safetyDetail.data && <><p className="text-sm">Evidence: {safetyDetail.data.evidence?.length ?? 0} · Reviewer actions: {safetyDetail.data.reviewer_actions?.length ?? 0} · Communications: {safetyDetail.data.communications?.length ?? 0}</p><div className="space-y-2">{safetyDetail.data.reviewer_actions?.map((action: any) => <div className="text-sm border-l-2 border-primary pl-3" key={action.id}><p>{action.action}</p><p className="text-xs text-foreground-muted">{action.created_at}</p></div>)}</div></>}</div>}
    </section>

    <section className="glass-card p-6 rounded-3xl border-border space-y-5" aria-labelledby="reputation-ops-title">
      <div className="flex items-center gap-2"><AlertTriangle size={18} aria-hidden="true" /><h2 id="reputation-ops-title" className="font-black uppercase tracking-wide">Reputation moderation</h2></div><p className="text-sm text-foreground-muted">Report dan allegation tidak otomatis menghukum actor. Setiap keputusan menyimpan reason, rule version, actor, dan audit.</p><QueryState loading={reviews.isLoading} error={Boolean(reviews.error)} /><div className="space-y-2">{reviews.data?.map((item: any) => <div className="rounded-2xl bg-surface-subtle p-4 grid gap-3 md:grid-cols-[1fr_auto]" key={item.id}><div><p className="font-bold">{item.stars}/5 · {item.service_code} · {item.state}</p><p className="text-sm">{item.body || 'Tanpa komentar'}</p><p className="text-xs text-foreground-muted">review {item.id} · subject {item.subject_id}</p></div><div className="flex gap-2"><select aria-label={`Moderation state ${item.id}`} className={inputClass} value={reviewState[item.id] || 'IN_REVIEW'} onChange={e => setReviewState({ ...reviewState, [item.id]: e.target.value })}><option value="IN_REVIEW">In review</option><option value="HIDDEN">Hide</option><option value="PUBLISHED">Restore</option></select><button type="button" disabled={reviewMutation.isPending} onClick={() => reviewMutation.mutate({ id: item.id, state: reviewState[item.id] || 'IN_REVIEW' })} className="rounded-xl bg-primary text-on-primary px-4 font-bold">Apply</button></div></div>)}</div></section>

    <section className="glass-card p-6 rounded-3xl border-border space-y-5" aria-labelledby="crm-ops-title">
      <div className="flex items-center gap-2"><Megaphone size={18} aria-hidden="true" /><h2 id="crm-ops-title" className="font-black uppercase tracking-wide">CRM / campaign control</h2></div><p className="text-sm text-foreground-muted">Audience, consent, budget, holdout, funding, dan loyalty liability tetap terpisah. Campaign baru dibuat sebagai DRAFT.</p><QueryState loading={crm.isLoading} error={Boolean(crm.error)} /><div className="grid gap-3 md:grid-cols-3"><input aria-label="Campaign code" className={inputClass} placeholder="campaign code" value={campaign.campaign_code} onChange={e => setCampaign({ ...campaign, campaign_code: e.target.value })} /><input aria-label="Campaign market" className={inputClass} value={campaign.market_code} onChange={e => setCampaign({ ...campaign, market_code: e.target.value })} /><input aria-label="Campaign budget" type="number" min="0" className={inputClass} value={campaign.budget_minor} onChange={e => setCampaign({ ...campaign, budget_minor: e.target.value })} /><button type="button" disabled={campaignMutation.isPending || !campaign.campaign_code} onClick={() => campaignMutation.mutate()} className="rounded-xl bg-primary text-on-primary p-3 font-bold md:col-span-3 disabled:opacity-50">Create draft (TOTP)</button></div><div className="grid gap-3 md:grid-cols-3">{crm.data?.campaigns?.map((item: any) => <div className="rounded-2xl bg-surface-subtle p-4" key={item.id}><p className="font-bold">{item.campaign_code}</p><p className="text-sm">{item.market_code} · {item.state}</p><p className="text-sm">Budget {formatMoney(item.budget_minor)}</p></div>)}</div><p className="text-sm text-foreground-muted">Loyalty accounts: <strong>{crm.data?.loyalty?.reduce((sum: number, item: any) => sum + Number(item.accounts || 0), 0) ?? 0}</strong> · Open CRM exceptions: <strong>{crm.data?.exceptions?.length ?? 0}</strong>.</p></section>
  </div>
}
