-- +goose Up
CREATE TABLE IF NOT EXISTS delivery_service_products (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  code VARCHAR(50) UNIQUE NOT NULL,
  name VARCHAR(100) NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  service_family VARCHAR(30) NOT NULL DEFAULT 'p2p',
  route_model VARCHAR(20) NOT NULL DEFAULT 'p2p' CHECK (route_model IN ('p2p', 'two_legs', 'three_legs')),
  is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  display_order INTEGER NOT NULL DEFAULT 100,
  vehicle_types TEXT[] NOT NULL DEFAULT ARRAY['motor'],
  exclusive_driver BOOLEAN NOT NULL DEFAULT TRUE,
  batching_allowed BOOLEAN NOT NULL DEFAULT FALSE,
  max_eta_minutes INTEGER NOT NULL DEFAULT 240,
  max_distance_km NUMERIC(8,2),
  max_weight_kg NUMERIC(8,2),
  uses_size_tier BOOLEAN NOT NULL DEFAULT TRUE,
  requires_dimension_scan BOOLEAN NOT NULL DEFAULT FALSE,
  allows_manual_dimension BOOLEAN NOT NULL DEFAULT FALSE,
  requires_pickup_verification BOOLEAN NOT NULL DEFAULT TRUE,
  price_mode VARCHAR(30) NOT NULL DEFAULT 'final' CHECK (price_mode IN ('final', 'estimated_then_adjusted')),
  base_fare_idr INTEGER NOT NULL DEFAULT 10000,
  included_distance_km NUMERIC(8,2) NOT NULL DEFAULT 1,
  per_km_idr INTEGER NOT NULL DEFAULT 4000,
  service_multiplier NUMERIC(8,4) NOT NULL DEFAULT 1,
  size_tiers JSONB NOT NULL DEFAULT '[]'::jsonb,
  dimension_rules JSONB NOT NULL DEFAULT '{}'::jsonb,
  availability_rules JSONB NOT NULL DEFAULT '{}'::jsonb,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE orders ADD COLUMN IF NOT EXISTS service_code VARCHAR(50);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS service_snapshot JSONB;

CREATE INDEX IF NOT EXISTS idx_delivery_service_products_enabled
  ON delivery_service_products (is_enabled, display_order);

CREATE INDEX IF NOT EXISTS idx_orders_service_code
  ON orders (service_code);

INSERT INTO delivery_service_products (
  code, name, description, service_family, route_model, is_enabled, display_order,
  vehicle_types, exclusive_driver, batching_allowed, max_eta_minutes, max_distance_km, max_weight_kg,
  uses_size_tier, requires_dimension_scan, allows_manual_dimension, requires_pickup_verification,
  price_mode, base_fare_idr, included_distance_km, per_km_idr, service_multiplier,
  size_tiers, dimension_rules, metadata
) VALUES
(
  'tembus_priority',
  'TEMBUS Prioritas',
  'P2P paling cepat untuk paket kecil dan urgent.',
  'p2p',
  'p2p',
  TRUE,
  10,
  ARRAY['motor'],
  TRUE,
  FALSE,
  120,
  40,
  20,
  TRUE,
  FALSE,
  TRUE,
  TRUE,
  'final',
  12000,
  1,
  4500,
  1.1500,
  '[{"code":"small","name":"Kecil","description":"Dokumen atau barang kecil","max_weight_kg":5,"price_delta_idr":0,"multiplier":1},{"code":"medium","name":"Sedang","description":"Tas kecil atau dus sedang","max_weight_kg":10,"price_delta_idr":4000,"multiplier":1.08},{"code":"large","name":"Besar","description":"Paket besar ringan","max_weight_kg":20,"price_delta_idr":9000,"multiplier":1.18}]',
  '{"volumetric_divisor":6000,"surcharge_threshold_kg":20,"surcharge_per_kg_idr":2500}',
  '{"ui_badge":"Maks. 2 jam"}'
),
(
  'tembus_instant',
  'TEMBUS Instant',
  'P2P langsung ke tujuan dengan satu kurir.',
  'p2p',
  'p2p',
  TRUE,
  20,
  ARRAY['motor'],
  TRUE,
  FALSE,
  240,
  70,
  20,
  TRUE,
  FALSE,
  TRUE,
  TRUE,
  'final',
  10000,
  1,
  4000,
  1.0000,
  '[{"code":"small","name":"Kecil","description":"Dokumen atau barang kecil","max_weight_kg":5,"price_delta_idr":0,"multiplier":1},{"code":"medium","name":"Sedang","description":"Tas kecil atau dus sedang","max_weight_kg":10,"price_delta_idr":3000,"multiplier":1.05},{"code":"large","name":"Besar","description":"Paket besar ringan","max_weight_kg":20,"price_delta_idr":7000,"multiplier":1.12}]',
  '{"volumetric_divisor":6000,"surcharge_threshold_kg":20,"surcharge_per_kg_idr":2000}',
  '{"ui_badge":"Maks. 4 jam"}'
),
(
  'tembus_hemat',
  'TEMBUS Hemat',
  'P2P ekonomis untuk jarak pendek.',
  'p2p',
  'p2p',
  TRUE,
  30,
  ARRAY['motor'],
  TRUE,
  FALSE,
  300,
  40,
  15,
  TRUE,
  FALSE,
  TRUE,
  TRUE,
  'final',
  9000,
  1,
  3500,
  0.9000,
  '[{"code":"small","name":"Kecil","description":"Dokumen atau barang kecil","max_weight_kg":5,"price_delta_idr":0,"multiplier":1},{"code":"medium","name":"Sedang","description":"Tas kecil atau dus sedang","max_weight_kg":10,"price_delta_idr":2500,"multiplier":1.04},{"code":"large","name":"Besar","description":"Paket besar ringan","max_weight_kg":15,"price_delta_idr":6000,"multiplier":1.1}]',
  '{"volumetric_divisor":6000,"surcharge_threshold_kg":15,"surcharge_per_kg_idr":2000}',
  '{"ui_badge":"Ekonomis"}'
),
(
  'tembus_same_day',
  'TEMBUS Same Day',
  'Pengiriman lebih ekonomis dengan batching operasional.',
  'same_day',
  'p2p',
  TRUE,
  40,
  ARRAY['motor'],
  FALSE,
  TRUE,
  480,
  70,
  20,
  TRUE,
  FALSE,
  TRUE,
  TRUE,
  'final',
  8000,
  1,
  3200,
  0.8200,
  '[{"code":"small","name":"Kecil","description":"Dokumen atau barang kecil","max_weight_kg":5,"price_delta_idr":0,"multiplier":1},{"code":"medium","name":"Sedang","description":"Tas kecil atau dus sedang","max_weight_kg":10,"price_delta_idr":2000,"multiplier":1.04},{"code":"large","name":"Besar","description":"Paket besar ringan","max_weight_kg":20,"price_delta_idr":5000,"multiplier":1.1}]',
  '{"volumetric_divisor":6000,"surcharge_threshold_kg":20,"surcharge_per_kg_idr":1800}',
  '{"ui_badge":"6-8 jam"}'
),
(
  'tembus_mobil',
  'TEMBUS Mobil',
  'P2P untuk paket besar atau banyak memakai mobil.',
  'p2p',
  'p2p',
  TRUE,
  50,
  ARRAY['car'],
  TRUE,
  FALSE,
  240,
  150,
  100,
  FALSE,
  TRUE,
  FALSE,
  TRUE,
  'final',
  30000,
  1,
  6500,
  1.0000,
  '[]',
  '{"volumetric_divisor":6000,"surcharge_threshold_kg":20,"surcharge_per_kg_idr":2500}',
  '{"ui_badge":"Mobil"}'
)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  service_family = EXCLUDED.service_family,
  route_model = EXCLUDED.route_model,
  display_order = EXCLUDED.display_order,
  vehicle_types = EXCLUDED.vehicle_types,
  exclusive_driver = EXCLUDED.exclusive_driver,
  batching_allowed = EXCLUDED.batching_allowed,
  max_eta_minutes = EXCLUDED.max_eta_minutes,
  max_distance_km = EXCLUDED.max_distance_km,
  max_weight_kg = EXCLUDED.max_weight_kg,
  uses_size_tier = EXCLUDED.uses_size_tier,
  requires_dimension_scan = EXCLUDED.requires_dimension_scan,
  allows_manual_dimension = EXCLUDED.allows_manual_dimension,
  requires_pickup_verification = EXCLUDED.requires_pickup_verification,
  price_mode = EXCLUDED.price_mode,
  base_fare_idr = EXCLUDED.base_fare_idr,
  included_distance_km = EXCLUDED.included_distance_km,
  per_km_idr = EXCLUDED.per_km_idr,
  service_multiplier = EXCLUDED.service_multiplier,
  size_tiers = EXCLUDED.size_tiers,
  dimension_rules = EXCLUDED.dimension_rules,
  metadata = EXCLUDED.metadata,
  updated_at = NOW();

-- +goose Down
DROP TABLE IF EXISTS delivery_service_products;
ALTER TABLE orders DROP COLUMN IF EXISTS service_code;
ALTER TABLE orders DROP COLUMN IF EXISTS service_snapshot;

