FROM golang:1.25.11-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod tidy && go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o datalake-worker .

FROM alpine:3.22
RUN apk upgrade --no-cache
RUN apk add --no-cache ca-certificates tzdata

WORKDIR /app
COPY --from=builder /app/datalake-worker .

CMD ["./datalake-worker"]
# trigger security scan

