import { useEffect, useState } from 'react'
import { Download } from 'lucide-react'
import { toast } from 'sonner'
import { api, apiBaseUrl, apiErrorMessage } from '../lib/api'
import { getToken } from '../lib/auth'
import type { SalesReportSummary } from '../lib/types'
import { rupiah } from '../lib/types'
import { MerchantPageSkeleton } from '../components/Skeleton'

export default function Reports() {
  const [period, setPeriod] = useState<'daily' | 'weekly'>('weekly')
  const [report, setReport] = useState<SalesReportSummary | null>(null)
  const [loading, setLoading] = useState(true)
  useEffect(() => { setLoading(true); api.get<SalesReportSummary>(`/merchant/reports?period=${period}`).then((res) => setReport(res.data)).catch((err) => toast.error(apiErrorMessage(err, 'Gagal memuat laporan'))).finally(() => setLoading(false)) }, [period])
  const download = async () => { try { const res = await fetch(`${apiBaseUrl}/merchant/reports/export?period=${period}`, { headers: { Authorization: `Bearer ${getToken()}` } }); if (!res.ok) throw new Error('Export gagal'); const blob = await res.blob(); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `laporan-merchant-${period}.csv`; a.click(); URL.revokeObjectURL(url) } catch (err) { toast.error(apiErrorMessage(err, 'Gagal mengunduh laporan')) } }
  return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-black text-zinc-900">Laporan penjualan</h1><p className="mt-1 text-sm text-zinc-500">Angka hanya berasal dari order dan rating di database.</p></div><div className="flex gap-2"><select value={period} onChange={(e) => setPeriod(e.target.value as 'daily' | 'weekly')} className="rounded-xl border border-zinc-200 bg-white px-3 py-2.5 text-sm font-bold"><option value="daily">Hari ini</option><option value="weekly">7 hari</option></select><button onClick={download} className="inline-flex items-center gap-2 rounded-xl bg-[#003A20] px-4 py-2.5 text-sm font-bold text-white"><Download className="h-4 w-4" /> CSV</button></div></div>{loading ? <MerchantPageSkeleton /> : report ? <><div className="grid gap-4 sm:grid-cols-3"><Stat label="Order selesai" value={String(report.total_orders)} /><Stat label="GMV" value={rupiah(report.gmv_idr)} /><Stat label="Rata-rata order" value={rupiah(report.avg_order_value_idr)} /></div><PerformanceCard performance={report.performance} /><AdvancedCard advanced={report.advanced} /><div className="grid gap-6 lg:grid-cols-2"><section className="rounded-[1.75rem] border border-zinc-100 bg-white p-6 shadow-sm"><h2 className="font-black">Item terlaris</h2>{(report.top_items || []).length === 0 ? <p className="py-8 text-sm text-zinc-400">Belum ada transaksi delivered.</p> : <ul className="mt-4 divide-y divide-zinc-100">{report.top_items?.map((item) => <li key={item.item_name} className="flex justify-between gap-3 py-3 text-sm"><span className="font-bold">{item.item_name} <span className="font-normal text-zinc-400">×{item.quantity}</span></span><span>{rupiah(item.revenue_idr)}</span></li>)}</ul>}</section><section className="rounded-[1.75rem] border border-zinc-100 bg-white p-6 shadow-sm"><h2 className="font-black">Pendapatan harian</h2><ul className="mt-4 divide-y divide-zinc-100">{(report.daily_breakdown || []).map((point) => <li key={point.day} className="flex justify-between py-3 text-sm"><span>{point.day}</span><b>{rupiah(point.revenue_idr)}</b></li>)}</ul></section></div></> : <p className="rounded-2xl bg-white p-8 text-center text-sm text-zinc-500">Belum ada data laporan.</p>}</div>
}
function Stat({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border border-zinc-100 bg-white p-5 shadow-sm"><p className="text-xs font-bold uppercase tracking-wide text-zinc-400">{label}</p><p className="mt-2 text-xl font-black text-emerald-950">{value}</p></div> }
function PerformanceCard({ performance }: { performance?: SalesReportSummary['performance'] }) { return <section className="rounded-[1.75rem] border border-zinc-100 bg-white p-6 shadow-sm"><div className="flex items-start justify-between gap-3"><div><h2 className="font-black">Performa operasional</h2><p className="mt-1 text-sm text-zinc-500">Dihitung dari semua order food pada periode ini.</p></div><span className="text-lg font-black text-amber-500">★ {performance?.avg_rating?.toFixed(1) ?? '0.0'}</span></div><div className="mt-5 grid gap-3 sm:grid-cols-4"><Metric label="Order masuk" value={String(performance?.total_received ?? 0)} /><Metric label="Acceptance" value={`${(performance?.acceptance_rate_pct ?? 0).toFixed(1)}%`} /><Metric label="Dibatalkan" value={`${performance?.cancelled ?? 0} (${(performance?.cancellation_rate_pct ?? 0).toFixed(1)}%)`} /><Metric label="Ditolak merchant" value={String(performance?.rejected_by_merchant ?? 0)} /></div></section> }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl bg-zinc-50 p-4"><p className="text-xs font-bold uppercase tracking-wide text-zinc-400">{label}</p><p className="mt-2 text-lg font-black text-emerald-950">{value}</p></div> }
function AdvancedCard({ advanced }: { advanced?: SalesReportSummary['advanced'] }) { return <section className="rounded-[1.75rem] border border-zinc-100 bg-white p-6 shadow-sm"><div><h2 className="font-black">Wawasan lanjutan</h2><p className="mt-1 text-sm text-zinc-500">Dihitung dari transaksi delivered pada periode yang dipilih.</p></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><Metric label="Pelanggan repeat" value={advanced ? `${advanced.repeat_customer_count} (${advanced.repeat_customer_rate_pct.toFixed(1)}%)` : 'Belum ada data'} /><Metric label="Jam tersibuk" value={advanced?.peak_order_hour != null ? `${String(advanced.peak_order_hour).padStart(2, '0')}:00 WIB` : 'Belum ada data'} /><Metric label="Accepted → ready" value={advanced?.avg_accepted_ready_minutes != null ? `${advanced.avg_accepted_ready_minutes.toFixed(1)} menit` : 'Belum ada data'} /></div></section> }
