import { useEffect, useState } from 'react'
import { Wallet } from 'lucide-react'
import { toast } from 'sonner'
import { api, apiErrorMessage } from '../lib/api'
import type { SettlementSummary, WithdrawalRecord } from '../lib/types'
import { rupiah } from '../lib/types'
import { MerchantPageSkeleton } from '../components/Skeleton'

export default function Settlements() {
  const [summary, setSummary] = useState<SettlementSummary | null>(null)
  const [withdrawals, setWithdrawals] = useState<WithdrawalRecord[]>([])
  const [loading, setLoading] = useState(true)
  const [amount, setAmount] = useState('')
  const [bank, setBank] = useState({ name: '', number: '', holder: '' })
  const [saving, setSaving] = useState(false)
  const load = () => Promise.all([api.get<SettlementSummary>('/merchant/settlements'), api.get<WithdrawalRecord[]>('/merchant/withdrawals')]).then(([s, w]) => { setSummary(s.data); setWithdrawals(w.data || []) }).catch((err) => toast.error(apiErrorMessage(err, 'Gagal memuat settlement'))).finally(() => setLoading(false))
  useEffect(() => { load() }, [])
  const withdraw = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); try { await api.post('/merchant/withdraw', { amount_idr: Number(amount), bank_name: bank.name, bank_account_number: bank.number, bank_account_holder: bank.holder, idempotency_key: crypto.randomUUID() }); toast.success('Permintaan pencairan diterima'); setAmount(''); await load() } catch (err) { toast.error(apiErrorMessage(err, 'Gagal mengajukan pencairan')) } finally { setSaving(false) } }
  if (loading) return <MerchantPageSkeleton />
  return <div className="space-y-6"><div><h1 className="text-2xl font-black text-zinc-900">Settlement</h1><p className="mt-1 text-sm text-zinc-500">Saldo dan pencairan diambil dari ledger merchant.</p></div><div className="grid gap-4 sm:grid-cols-3"><Stat label="Bisa ditarik" value={rupiah(summary?.available_idr || 0)} accent /><Stat label="Sudah cair" value={rupiah(summary?.total_idr || 0)} /><Stat label="Ditahan / proses" value={rupiah(summary?.holding_idr || 0)} /></div><form onSubmit={withdraw} className="grid gap-4 rounded-[1.75rem] border border-zinc-100 bg-white p-6 shadow-sm md:grid-cols-2"><h2 className="font-black md:col-span-2">Ajukan pencairan</h2><label className="text-sm font-bold">Nominal<input required type="number" min="1" value={amount} onChange={(e) => setAmount(e.target.value)} placeholder="Nominal IDR" className="mt-1 w-full rounded-xl border border-zinc-200 px-3 py-3 font-normal" /></label><label className="text-sm font-bold">Nama bank<input required value={bank.name} onChange={(e) => setBank({ ...bank, name: e.target.value })} className="mt-1 w-full rounded-xl border border-zinc-200 px-3 py-3 font-normal" /></label><label className="text-sm font-bold">Nomor rekening<input required value={bank.number} onChange={(e) => setBank({ ...bank, number: e.target.value })} className="mt-1 w-full rounded-xl border border-zinc-200 px-3 py-3 font-normal" /></label><label className="text-sm font-bold">Nama pemilik rekening<input required value={bank.holder} onChange={(e) => setBank({ ...bank, holder: e.target.value })} className="mt-1 w-full rounded-xl border border-zinc-200 px-3 py-3 font-normal" /></label><button disabled={saving} className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#003A20] px-5 py-3 font-bold text-white disabled:opacity-60 md:col-span-2"><Wallet className="h-4 w-4" /> {saving ? 'Memproses…' : 'Ajukan pencairan'}</button></form><section className="rounded-[1.75rem] border border-zinc-100 bg-white p-6 shadow-sm"><h2 className="font-black">Riwayat settlement</h2>{!summary?.records?.length ? <p className="py-8 text-sm text-zinc-400">Belum ada settlement.</p> : <div className="mt-4 divide-y divide-zinc-100">{summary.records.map((record) => <div key={record.id} className="flex flex-wrap justify-between gap-2 py-3 text-sm"><span><b>{rupiah(record.net_payout_idr)}</b><span className="ml-2 text-zinc-400">{new Date(record.created_at).toLocaleDateString('id-ID')}</span></span><span className="font-bold text-zinc-500">{record.status}</span></div>)}</div>}</section><section className="rounded-[1.75rem] border border-zinc-100 bg-white p-6 shadow-sm"><h2 className="font-black">Riwayat pencairan</h2>{!withdrawals.length ? <p className="py-8 text-sm text-zinc-400">Belum ada permintaan pencairan.</p> : withdrawals.map((item) => <div key={item.id} className="flex justify-between border-b border-zinc-100 py-3 text-sm"><span>{rupiah(item.amount_idr)} · {item.bank_name}</span><b>{item.status}</b></div>)}</section></div>
}
function Stat({ label, value, accent }: { label: string; value: string; accent?: boolean }) { return <div className={`rounded-2xl border p-5 shadow-sm ${accent ? 'border-orange-200 bg-orange-50' : 'border-zinc-100 bg-white'}`}><p className="text-xs font-bold uppercase tracking-wide text-zinc-400">{label}</p><p className="mt-2 text-xl font-black text-emerald-950">{value}</p></div> }
